name = "50501 Santa Cruz"
description = "Santa Cruz Chapter of the 50501 Movement"
keywords = "50501, Santa Cruz, protest"
image = "SantaCruzLogo.png"
theme = "dark"
primary_color = "#1e49c6"
text_align = "center"
base_url = "https://50501santacruz.github.io/"

[[sections]]
title = "Next Event"
item_style = "outline"
direction = "row"
icon_size = "1000px"
[[sections.items]]
icon = "maydaystrongflyer.png"

[[sections]]
title = "Volunteer With Us"
description = "Help Us Organize Epic Protests!"
direction = "column"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
title = "Volunteer Sign-up"
url = "https://cryptpad.fr/form/#/2/form/view/-0Ft6rtDhFbyFOmseFi0w+R9uFzjXmGgDkaBopd8rAo/"

[[sections]]
title = "Contact Us"
direction = "column"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
title = "Email"
url = "mailto:santacruz@50501.ca"

[[sections]]
title = "Links"
description = "Follow us on Social Media"
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/bluesky/ffffff"
title = "Bluesky"
url = "https://bsky.app/profile/50501santacruz.bsky.social"
[[sections.items]]
icon = "https://cdn.simpleicons.org/x/ffffff"
title = "X.com"
url = "https://x.com/50501SantaCruz"
[[sections.items]]
icon = "https://cdn.simpleicons.org/lemmy/ffffff"
title = "Lemmy"
url = "https://50501.chat/u/santacruz"

[[sections]]
title = "50501 California"
description = "Learn more about the 50501 movement in California"
item_style = "outline"
icon_size = "45px"
[[sections.items]]
icon = "https://50501.ca/static/media/california.a946446044a9ee9faec3.png"
title = "Visit 50501.ca"
url = "https://50501.ca/"

[[sections]]
title = "Our Friends and Partners"
description = "Check out these other local activism groups"
direction = "row"
item_style = "outline"
icon_size = "100px"
[[sections.items]]
icon = "https://images.squarespace-cdn.com/content/v1/65e24eb0339d3355610d8848/ff5726a8-4e00-4013-8fc7-94f6ead06c9b/ISCC+Logo_Transparent_large.png?format=1500w"
title = "Indivisible Santa Cruz County"
url = "https://www.indivisiblesantacruzcounty.com/"
